#!/usr/bin/env python
# $Id$
"""\
 mqadd - low-level submit
 Manual queuing system, Created 2006-11-07 Ian McCulloch

 bugs: probably lots
"""

from mqcommon import *

def main():
    argv = sys.argv[1:]
    # if we are not running on the frontend node, ssh there
    if socket.gethostname() != ExecHost:
        argv[0:0] = [ExecHost,'mqassertadd']
        print argv
        os.execv("/usr/bin/ssh", argv)

    AddToRunQueue(argv)
    TrySubmitJobs()

if __name__ == '__main__': main()
