#!/usr/bin/env python
# $Id$
"""\
 mqassert - functions like mq but we can only run it on the frontend node
 (this is to prevent a loop if the ExecName differs from the hostname returned
 by gethostname())
 Manual queuing system, Created 2006-11-07 Ian McCulloch

 bugs: probably lots
"""

from mqcommon import *

def main():
    # if we are not running on the frontend node, ssh there
    if socket.gethostname() != ExecHost:
        print('mq: error: expecting mqassert to be called from host '
              +ExecHost+', but it was called from host '+socket.gethostname())
        sys.exit(2)

    NumQueued = QueuedCount()
    ToQueue = MaxQueueLength-NumQueued
    if ToQueue > 0:
        SubmitJobs(ToQueue)

if __name__ == '__main__': main()
