name: C/C++ CI

on:
  push:
    branches: [ "main", "tdvp" ]
  pull_request:
    branches: [ "main", "tdvp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
       sudo apt-get -y update
       sudo apt-get -y install libboost-all-dev libarpack2-dev
    - name: configure
      run: CXXFLAGS=-O0 ./configure --with-openmp
    - name: make
      run: make
#    - name: make models
#      run: make models
