name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
       sudo apt-get -y update
       sudo apt-get -y install libboost-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make models
      run: make models
